### ISSUE TITLE
Wrong order of tracks

### ISSUE THREAD

**Issue by WingedRat** [apognu/otter#13]
Tracks have the wrong order, while everything's okay via web interface

Funkwhale 0.20.1 / Otter 1.0.15

![Screenshot_20191122-163429_Otter](https://user-images.githubusercontent.com/10961696/69430069-03bfe180-0d46-11ea-9ae2-26836325ed5c.png)

**Comment by apognu** [comment]
Thanks for reporting.

I do not sort tracks for the moment, assuming natural array order would be fine. But I'll see if I can use the `position` attribute to order them properly.

I'll see what I can do for 1.0.16.

**Comment by f1xmAn** [comment]
That would be really useful if you implement tracks ordering in the next release. I believe nobody wants to listen to album tracks in the wrong order. :)

**Comment by grondinm** [comment]
This is the one thing that drives me crazy using otter. Otherwise works perfect.

Thank you for the great app.

**Comment by datadog2017** [comment]
It would be much appreciated if you could implement ordering by track number (position attribute)!

Thanks for creating a beautiful Funkwhale client! 

P.S.: Where can we make some beer donations!?

**Comment by apognu** [comment]
Hi,

Sorry about the (very long) delay.

This should be fixed in 1.0.16 which is now being deployed on Google Play. Please reopen if you still notice any strange behavior in the track sort order.

**Comment by grondinm** [comment]
Thank you so much for addressing this. I will update and advise if i 
still see anything odd.

Thank you again for the great app

Marc

**Comment by Atilir** [comment]
Hi,

The problem as reappeared and I updated otter to 1.0.20 and updated my funkwhale version to 0.21.2. I don't know if this caused any issue.

Thanks.
